Import EPA fuel economy data from 2009-2025

In [3]:
import pandas as pd

#xlsx
data_25 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\25-testcar-2025-05.xlsx")
data_24 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\24-testcar-2025-05.xlsx")
data_23 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\23-testcar-2024-05-17_0.xlsx")
data_22 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\22-testcar-2023-06-13.xlsx")
data_21 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\21-tstcar-2022-04-15.xlsx")
data_20 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\20tstcar-2021-03-02.xlsx")
data_19 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\19tstcar-2020-10-02.xlsx")
data_18 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\18tstcar-2018-10-24.xlsx")
data_17 = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\17tstcar-2018-05-30.xlsx")

#csv
data_16 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\16tstcar.csv")
data_15 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\15tstcar.csv")
data_14 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\14tstcar.csv")
data_13 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\13tstcar.csv")
data_12 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\12tstcar.csv")
data_11 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\11tstcar.csv")
data_10 = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\10tstcar.csv")
data_09lr = pd.read_csv(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\CSV\09tstcar-laterelease.csv")

Convert data to dataframes to begin cleaning

In [4]:
df_25 = pd.DataFrame(data_25)
df_24 = pd.DataFrame(data_24)
df_23 = pd.DataFrame(data_23)
df_22 = pd.DataFrame(data_22)
df_21 = pd.DataFrame(data_21)
df_20 = pd.DataFrame(data_20)
df_19 = pd.DataFrame(data_19)
df_18 = pd.DataFrame(data_18)
df_17 = pd.DataFrame(data_17)
df_16 = pd.DataFrame(data_16)
df_15 = pd.DataFrame(data_15)
df_14 = pd.DataFrame(data_14)
df_13 = pd.DataFrame(data_13)
df_12 = pd.DataFrame(data_12)
df_11 = pd.DataFrame(data_11)
df_10 = pd.DataFrame(data_10)
df_09lr = pd.DataFrame(data_09lr)

Append dataframes for 2017-2025 into one dataframe, and 2009-2016 into one dataframe

In [5]:
merged_17to25 = pd.concat([df_25,df_24,df_23,df_22,df_21,df_20,df_19,df_18,df_17], ignore_index=True)
merged_09to16 = pd.concat([df_16,df_15,df_14,df_13,df_12,df_11,df_10,df_09lr], ignore_index=True)

In [6]:
merged_17to25.head(2)

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,...,Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
0,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.0,RASXV04.0AES,Car,...,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
1,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.0,RASXV04.0AES,Car,...,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging

In [7]:
merged_17to25.tail(2)

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,...,Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
40391,2017,Volvo,VVX,Volvo,XC90 T8 AWD,201621,1,1.969,GVVXT02.0P3T,Truck,...,-0.6,-0.186,0.0278,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
40392,2017,Volvo,VVX,Volvo,XC90 T8 AWD,201621,1,1.969,GVVXT02.0P3T,Truck,...,-0.6,-0.186,0.0278,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging

In [8]:
merged_09to16.head(2)

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,...,Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
0,2016,aston martin,ASX,Aston Martin,DB9,143TT1042,0,5.9,DASXV05.9VH1,Car,...,8.35,0.299,0.0192,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
1,2016,aston martin,ASX,Aston Martin,DB9,143TT1042,0,5.9,DASXV05.9VH1,Car,...,8.35,0.299,0.0192,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging

In [9]:
merged_09to16.tail(2)

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,...,Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
29935,2009,Volvo,VVX,Volvo,S40 2.4i FWD,200806,2,2.435,AVVXV02.4U2N,Car,...,13.92,0.1811,0.0173,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
29936,2009,Volvo,VVX,Volvo,S40 2.4i FWD,200806,2,2.435,AVVXV02.4U2N,Car,...,16.60,0.2410,0.0188,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging

In [10]:
merged_17to25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40393 entries, 0 to 40392
Data columns (total 67 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Model Year                      40393 non-null  int64
 1   Vehicle Manufacturer Name       40393 non-null  object
 2   Veh Mfr Code                    40393 non-null  object
 3   Represented Test Veh Make       40393 non-null  object
 4   Represented Test Veh Model      40393 non-null  object
 5   Test Vehicle ID                 40393 non-null  object
 6   Test Veh Configuration #        40393 non-null  int64
 7   Test Veh Displacement (L)       40393 non-null  float64
 8   Actual Tested Testgroup         40393 non-null  object
 9   Vehicle Type                    40393 non-null  object
 10  Rated Horsepower                40393 non-null  int64
 11  # of Cylinders and Rotors       37617 non-null  float64
 12  Engine Code                     40369 non-null  object
 13  Tested Transmission Type Code   40393 non-null  object
 14  Tested Transmission Type        40393 non-null  object
 15  # of Gears                      40393 non-null  int64
 16  Transmission Lockup?            40393 non-null  object
 17  Drive System Code               40393 non-null  object
 18  Drive System Description        40393 non-null  object
 19  Transmission Overdrive Code     40393 non-null  int64
 20  Transmission Overdrive Desc     40393 non-null  object
 21  Equivalent Test Weight (lbs.)   40393 non-null  int64
 22  Axle Ratio                      40393 non-null  float64
 23  N/V Ratio                       40393 non-null  float64
 24  Shift Indicator Light Use Cd    40393 non-null  int64
 25  Shift Indicator Light Use Desc  40393 non-null  object
 26  Test Number                     40393 non-null  object
 27  Test Originator                 40393 non-null  object
 28  Analytically Derived FE?        40393 non-null  object
 29  ADFE Test Number                4090 non-null   object
 30  ADFE Total Road Load HP         4090 non-null   float64
 31  ADFE Equiv. Test Weight (lbs.)  4090 non-null   float64
 32  ADFE N/V Ratio                  4090 non-null   float64
 33  Test Procedure Cd               40393 non-null  int64
 34  Test Procedure Description      40393 non-null  object
 35  Test Fuel Type Cd               40393 non-null  int64
 36  Test Fuel Type Description      40393 non-null  object
 37  Test Category                   40393 non-null  object
 38  THC (g/mi)                      34144 non-null  float64
 39  CO (g/mi)                       34313 non-null  float64
 40  CO2 (g/mi)                      36950 non-null  float64
 41  NOx (g/mi)                      34026 non-null  float64
 42  PM (g/mi)                       6332 non-null   float64
 43  CH4 (g/mi)                      31930 non-null  float64
 44  N2O (g/mi)                      19973 non-null  float64
 45  RND_ADJ_FE                      39573 non-null  float64
 46  FE_UNIT                         40393 non-null  object
 47  FE Bag 1                        18729 non-null  float64
 48  FE Bag 2                        18729 non-null  float64
 49  FE Bag 3                        15412 non-null  float64
 50  FE Bag 4                        1948 non-null   float64
 51  DT-Inertia Work Ratio Rating    35634 non-null  float64
 52  DT-Absolute Speed Change Ratg   35634 non-null  float64
 53  DT-Energy Economy Rating        35634 non-null  float64
 54  Target Coef A (lbf)             40393 non-null  float64
 55  Target Coef B (lbf/mph)         40393 non-null  float64
 56  Target Coef C (lbf/mph**2)      40393 non-null  float64
 57  Set Coef A (lbf)                40393 non-null  float64
 58  Set Coef B (lbf/mph)            40393 non-null  float64
 59  Set Coef C (lbf/mph**2)         40393 non-null  float64
 60  Aftertreatment Device Cd        37575 non-null  object
 61  Aftertreatment Device Desc      37575 non-null  object
 62  Police - Emergency Vehicle?     40393 non-null  object
 63  Averaging Group ID              1191 non-null   object
 64  Averaging Weighting Factor      1191 non-null   float64
 65  Averaging Method Cd             40393 non-null  object
 66  Averging Method Desc            40393 non-null  object
dtypes: float64(29), int64(9), object(29)
memory usage: 20.6+ MB

In [11]:
merged_09to16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29937 entries, 0 to 29936
Data columns (total 67 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Model Year                      29937 non-null  int64
 1   Vehicle Manufacturer Name       29937 non-null  object
 2   Veh Mfr Code                    29937 non-null  object
 3   Represented Test Veh Make       29937 non-null  object
 4   Represented Test Veh Model      29937 non-null  object
 5   Test Vehicle ID                 29937 non-null  object
 6   Test Veh Configuration #        29937 non-null  int64
 7   Test Veh Displacement (L)       29937 non-null  float64
 8   Actual Tested Testgroup         29937 non-null  object
 9   Vehicle Type                    29937 non-null  object
 10  Rated Horsepower                29937 non-null  int64
 11  # of Cylinders and Rotors       27535 non-null  float64
 12  Engine Code                     29937 non-null  object
 13  Tested Transmission Type Code   29937 non-null  object
 14  Tested Transmission Type        29937 non-null  object
 15  # of Gears                      29937 non-null  int64
 16  Transmission Lockup?            29937 non-null  object
 17  Drive System Code               29937 non-null  object
 18  Drive System Description        29937 non-null  object
 19  Transmission Overdrive Code     29937 non-null  int64
 20  Transmission Overdrive Desc     29937 non-null  object
 21  Equivalent Test Weight (lbs.)   29937 non-null  int64
 22  Axle Ratio                      29937 non-null  float64
 23  N/V Ratio                       29937 non-null  float64
 24  Shift Indicator Light Use Cd    29937 non-null  int64
 25  Shift Indicator Light Use Desc  29937 non-null  object
 26  Test Number                     29937 non-null  object
 27  Test Originator                 29937 non-null  object
 28  Analytically Derived FE?        29937 non-null  object
 29  ADFE Test Number                1689 non-null   object
 30  ADFE Total Road Load HP         1689 non-null   float64
 31  ADFE Equiv. Test Weight (lbs.)  1699 non-null   float64
 32  ADFE N/V Ratio                  1689 non-null   float64
 33  Test Procedure Cd               29937 non-null  int64
 34  Test Procedure Description      29937 non-null  object
 35  Test Fuel Type Cd               29937 non-null  int64
 36  Test Fuel Type Description      29937 non-null  object
 37  Test Category                   29937 non-null  object
 38  THC (g/mi)                      27665 non-null  float64
 39  CO (g/mi)                       27737 non-null  float64
 40  CO2 (g/mi)                      28522 non-null  float64
 41  NOx (g/mi)                      27484 non-null  float64
 42  PM (g/mi)                       2760 non-null   float64
 43  CH4 (g/mi)                      21040 non-null  float64
 44  N2O (g/mi)                      10754 non-null  float64
 45  RND_ADJ_FE                      29845 non-null  float64
 46  FE_UNIT                         29937 non-null  object
 47  FE Bag 1                        11111 non-null  float64
 48  FE Bag 2                        11023 non-null  float64
 49  FE Bag 3                        9516 non-null   float64
 50  FE Bag 4                        582 non-null    float64
 51  DT-Inertia Work Ratio Rating    4187 non-null   float64
 52  DT-Absolute Speed Change Ratg   4187 non-null   float64
 53  DT-Energy Economy Rating        4187 non-null   float64
 54  Target Coef A (lbf)             29937 non-null  float64
 55  Target Coef B (lbf/mph)         29937 non-null  float64
 56  Target Coef C (lbf/mph**2)      29937 non-null  float64
 57  Set Coef A (lbf)                29937 non-null  float64
 58  Set Coef B (lbf/mph)            29937 non-null  float64
 59  Set Coef C (lbf/mph**2)         29937 non-null  float64
 60  Aftertreatment Device Cd        26839 non-null  object
 61  Aftertreatment Device Desc      26839 non-null  object
 62  Police - Emergency Vehicle?     29937 non-null  object
 63  Averaging Group ID              1660 non-null   object
 64  Averaging Weighting Factor      1660 non-null   float64
 65  Averaging Method Cd             29937 non-null  object
 66  Averging Method Desc            29937 non-null  object
dtypes: float64(29), int64(9), object(29)
memory usage: 15.3+ MB

Filter out unnecessary columns

In [12]:
columns_to_keep = ['Veh Mfr Code', 'Represented Test Veh Make', 'Represented Test Veh Model',
                'Test Vehicle ID', 'Vehicle Type', 'Test Fuel Type Cd', 'Test Fuel Type Description',
                 'CO2 (g/mi)']
filtered_17to25 = merged_17to25[columns_to_keep]
filtered_09to16 = merged_09to16[columns_to_keep]

In [13]:
filtered_17to25.head()

,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Vehicle Type,Test Fuel Type Cd,Test Fuel Type Description,CO2 (g/mi)
0,ASX,Aston Martin,DB12 V8,5723PT5601,Car,61,Tier 2 Cert Gasoline,484.329
1,ASX,Aston Martin,DB12 V8,5723PT5601,Car,61,Tier 2 Cert Gasoline,283.235
2,ASX,Aston Martin,DBX 707,8841PT8473,Both,61,Tier 2 Cert Gasoline,486.750
3,ASX,Aston Martin,DBX 707,8841PT8473,Both,61,Tier 2 Cert Gasoline,331.480
4,ASX,Aston Martin,Vanquish,370TT7334,Car,61,Tier 2 Cert Gasoline,546.351

In [14]:
filtered_09to16.head()

,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Vehicle Type,Test Fuel Type Cd,Test Fuel Type Description,CO2 (g/mi)
0,ASX,Aston Martin,DB9,143TT1042,Car,61,Tier 2 Cert Gasoline,550.27
1,ASX,Aston Martin,DB9,143TT1042,Car,61,Tier 2 Cert Gasoline,343.88
2,ASX,Aston Martin,Rapide S,410TT4202,Car,61,Tier 2 Cert Gasoline,511.93
3,ASX,Aston Martin,Rapide S,410TT4202,Car,61,Tier 2 Cert Gasoline,296.63
4,ASX,Aston Martin,V12 Vantage S,288TT2087,Car,61,Tier 2 Cert Gasoline,603.49

Average CO2 emissions for cars of same make and model from different years

In [15]:
avg_17to25 = filtered_17to25.groupby(['Represented Test Veh Make', 'Represented Test Veh Model']).agg({
    'CO2 (g/mi)': 'mean',
    'Veh Mfr Code': 'first', 
    'Vehicle Type': 'first',
    'Test Vehicle ID': 'first'
}).reset_index()

avg_09to16 = filtered_09to16.groupby(['Represented Test Veh Make', 'Represented Test Veh Model']).agg({
    'CO2 (g/mi)': 'mean',
    'Veh Mfr Code': 'first',  
    'Vehicle Type': 'first',
    'Test Vehicle ID': 'first'
}).reset_index()

In [16]:
avg_17to25.head(30)

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
0,2022,Lucid Air Dream P,NaN,LMU,Car,2022111
1,2022,Lucid Air Dream R,NaN,LMU,Car,202252373
2,2022,Lucid Air Grand Touring,NaN,LMU,Car,202214319
3,2023,Lucid Air Touring,NaN,LMU,Car,2023252121
4,2024,"Air Pure RWD w/19"" wheels",NaN,LMU,Car,202400128
5,2024,"Air Pure RWD w/20"" wheels",NaN,LMU,Car,202400128
6,2024,Air Sapphire AWD,NaN,LMU,Car,202400084
7,2024,Lucid Air Grand Touring XR,NaN,LMU,Car,202401846
8,2024,Lucid Air Touring AWD,NaN,LMU,Car,202400005
9,2025,"Air Pure RWD w/19"" wheels",NaN,LMU,Car,202500034
10,2025,"Air Pure RWD w/20"" wheels",NaN,LMU,Car,202500034
11,2025,Lucid Gravity GT (2R),NaN,LMU,Car,2025G01033
12,2025,Lucid Gravity GT (3R),NaN,LMU,Car,2025G01034
13,ACURA,ADX AWD,233.475000,HNX,Car,ESVJ2C
14,ACURA,ADX FWD,221.080000,HNX,Car,ESVJ3C
15,ACURA,ILX,227.985000,HNX,Car,EK4H1D
16,ACURA,INTEGRA,239.378571,HNX,Car,EPLM1C
17,ACURA,INTEGRA A-SPEC,206.239250,HNX,Car,EPLM1C
18,ACURA,MDX AWD,313.575000,HNX,Truck,EM1A1A
19,ACURA,MDX AWD A-spec,310.665000,HNX,Car,EKBN1A
20,ACURA,MDX AWD Type-S,372.876667,HNX,Truck,EN1B1A
21,ACURA,MDX FWD,298.330000,HNX,Truck,EM1A2A
22,ACURA,NSX,299.235000,HNX,Car,EH8G1D
23,ACURA,RDX 2WD,286.670000,HNX,Truck,EGME2A
24,ACURA,RDX 4WD,299.450000,HNX,Truck,EGME1A
25,ACURA,RDX AWD,276.580000,HNX,Truck,EKYF2A
26,ACURA,RDX AWD A-SPEC,311.474667,HNX,Truck,EKYF2A
27,ACURA,RDX FWD,267.275000,HNX,Truck,EKYF3A
28,ACURA,RDX FWD A-SPEC,301.670000,HNX,Truck,EKYF3A
29,ACURA,RLX,284.023943,HNX,Car,EJ9P1A

In [17]:
avg_17to25.tail()

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
2312,Volvo,XC90 T5 FWD,274.153846,VVX,Both,202006
2313,Volvo,XC90 T6 AWD,312.519525,VVX,Both,202107
2314,Volvo,XC90 T8 AWD,264.231594,VVX,Both,202001
2315,Volvo,XC90 T8 AWD Recharge,245.000000,VVX,Both,202308
2316,Volvo,XC90 T8 AWD Recharge Extended Range,247.928139,VVX,Both,202211

In [18]:
avg_09to16.head()

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
0,ACURA,ILX,290.192174,HNX,Car,EG4H1D
1,ACURA,ILX HYBRID,184.771111,HNX,Car,ED9C2C
2,ACURA,MDX 2WD,288.207500,HNX,Car,EGJ62A
3,ACURA,MDX 4WD,341.777223,HNX,Car,EGJ61A
4,ACURA,RDX 2WD,287.412500,HNX,Truck,EGME2A

In [19]:
avg_09to16.tail()

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
1542,Volvo,XC90 T5 FWD,302.666667,VVX,Truck,201612
1543,Volvo,XC90 T6 AWD,323.750000,VVX,Truck,201601
1544,Volvo,XC90 T8 AWD,297.784250,VVX,Truck,201615
1545,Volvo,XC90 V8 AWD,483.571429,VVX,Truck,201101
1546,W204E63-Z1011,C 63 AMG,439.750000,MBX,Car,W204E63-Z1011

Drop rows that do not report any CO2 emissions

In [20]:
clean_17to25 = avg_17to25.dropna(subset=['CO2 (g/mi)'])
clean_09to16 = avg_09to16.dropna(subset=['CO2 (g/mi)'])

In [21]:
clean_17to25.head(20)

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
13,ACURA,ADX AWD,233.475000,HNX,Car,ESVJ2C
14,ACURA,ADX FWD,221.080000,HNX,Car,ESVJ3C
15,ACURA,ILX,227.985000,HNX,Car,EK4H1D
16,ACURA,INTEGRA,239.378571,HNX,Car,EPLM1C
17,ACURA,INTEGRA A-SPEC,206.239250,HNX,Car,EPLM1C
18,ACURA,MDX AWD,313.575000,HNX,Truck,EM1A1A
19,ACURA,MDX AWD A-spec,310.665000,HNX,Car,EKBN1A
20,ACURA,MDX AWD Type-S,372.876667,HNX,Truck,EN1B1A
21,ACURA,MDX FWD,298.330000,HNX,Truck,EM1A2A
22,ACURA,NSX,299.235000,HNX,Car,EH8G1D
23,ACURA,RDX 2WD,286.670000,HNX,Truck,EGME2A
24,ACURA,RDX 4WD,299.450000,HNX,Truck,EGME1A
25,ACURA,RDX AWD,276.580000,HNX,Truck,EKYF2A
26,ACURA,RDX AWD A-SPEC,311.474667,HNX,Truck,EKYF2A
27,ACURA,RDX FWD,267.275000,HNX,Truck,EKYF3A
28,ACURA,RDX FWD A-SPEC,301.670000,HNX,Truck,EKYF3A
29,ACURA,RLX,284.023943,HNX,Car,EJ9P1A
30,ACURA,RLX HYBRID,220.070407,HNX,Car,EJ9S1D
31,ACURA,TLX,244.467256,HNX,Car,EJDF1D
32,ACURA,TLX AWD,273.170000,HNX,Car,EMS81A

In [22]:
clean_09to16.head(30)

,Represented Test Veh Make,Represented Test Veh Model,CO2 (g/mi),Veh Mfr Code,Vehicle Type,Test Vehicle ID
0,ACURA,ILX,290.192174,HNX,Car,EG4H1D
1,ACURA,ILX HYBRID,184.771111,HNX,Car,ED9C2C
2,ACURA,MDX 2WD,288.207500,HNX,Car,EGJ62A
3,ACURA,MDX 4WD,341.777223,HNX,Car,EGJ61A
4,ACURA,RDX 2WD,287.412500,HNX,Truck,EGME2A
5,ACURA,RDX 4WD,298.827500,HNX,Truck,EGME1A
6,ACURA,RDX BASE/TECH,328.335000,HNX,Truck,EAWC1A
7,ACURA,RL,365.075000,HNX,Car,E9KG1A
8,ACURA,RLX HYBRID,217.686019,HNX,Car,EE9S1A
9,ACURA,TL 2WD,298.108000,HNX,Car,ECK11A
10,ACURA,TL 4WD,328.369000,HNX,Car,EAK21M
11,ACURA,TLX,246.027953,HNX,Both,DFDF1D
12,ACURA,TSX,272.908750,HNX,Car,EBL51A
13,ACURA,TSX V6,309.280000,HNX,Car,EAL81A
14,ACURA,TSX/TSX Premium,280.297015,HNX,Car,E9L51A
15,ACURA,ZDX 4WD,356.326889,HNX,Car,EAP61A
16,AUDI,A3,311.065343,VGA,Car,FAPA-AAF
17,AUDI,A3 QUATTRO,333.400000,ADX,Car,93UA-AAQ
18,AUDI,A3 e-tron,176.172118,VGA,Car,AU373-6-0813/16
19,AUDI,A4,304.504132,ADX,Car,D3UB-BAF
20,AUDI,A4 AVANT QUATTRO,291.668541,ADX,Car,93UB-BAQ
21,AUDI,A4 Allroad,285.750000,VGA,Both,FAUF-BAA
22,AUDI,A4 QUATTRO,308.375000,ADX,Car,93UB-BMQ
23,AUDI,A5,311.272727,ADX,Car,DFUB-BAQ
24,AUDI,A5 quattro,353.285714,ADX,Car,93UB-BAQ
25,AUDI,A6,336.161123,VGA,Car,GAUE-CAQ
26,AUDI,A6 QUATTRO,369.923077,ADX,Car,7365-CAQ
27,AUDI,A6 quattro,354.200000,ADX,Car,D3UB-CAQ
28,AUDI,A7,318.217191,VGA,Both,GNU4-CAQ
29,AUDI,A8,369.110631,ADX,Car,D3UG-DAQ

Export clean data to csv

In [23]:
clean_09to16.to_csv('09to16_models.csv')
clean_17to25.to_csv('17to25_models.csv')

Vehicle Type only CO2

In [30]:
type_only_17to25 = filtered_17to25.groupby(['Vehicle Type']).agg({
    'CO2 (g/mi)': 'mean',
}).reset_index()

type_only_09to16 = filtered_09to16.groupby(['Vehicle Type']).agg({
    'CO2 (g/mi)': 'mean',
}).reset_index()
type_only_09to16.head()

  Vehicle Type  CO2 (g/mi)
0         Both  306.266060
1          Car  305.495892
2        Truck  374.408104

In [29]:
type_only_17to25.head()

  Vehicle Type  CO2 (g/mi)
0         Both  288.690007
1          Car  293.973187
2        Truck  335.079088

Export vehicle Type only to CSV

In [31]:
type_only_17to25.to_csv('17to25_type_only.csv')
type_only_09to16.to_csv('09to16_type_only.csv')

type only CO2 all years

In [39]:

type_only_allyears = pd.merge(type_only_09to16, type_only_17to25, 
                 on='Vehicle Type',
                 suffixes=('_09to16', '_17to25'))


type_only_allyears['Average_CO2'] = (type_only_allyears['CO2 (g/mi)_09to16'] + type_only_allyears['CO2 (g/mi)_17to25']) / 2


type_only_allyears.head()

  Vehicle Type  CO2 (g/mi)_09to16  CO2 (g/mi)_17to25  Average_CO2
0         Both         306.266060         288.690007   297.478034
1          Car         305.495892         293.973187   299.734540
2        Truck         374.408104         335.079088   354.743596

In [45]:
columns_to_keep2 = ['Vehicle Type','Average_CO2']
type_only_allyears = type_only_allyears[columns_to_keep2]
type_only_allyears.head()

  Vehicle Type  Average_CO2
0         Both   297.478034
1          Car   299.734540
2        Truck   354.743596

In [46]:
type_only_allyears.to_csv('type_only_allyears.csv')