In [7]:

import numpy as np
import pandas as pd
from scipy.stats import trim_mean

In [5]:
import pandas as pd

data = pd.read_excel(r"C:\Users\clair\Senior-Project\EPA Data Cleaning\Raw Data\Excel\ExtraEPAData_diesel.xlsx")

In [6]:
df = pd.DataFrame(data)
df.head(10)

,Unnamed: 0,(R) 2000,(R) 2001,(R) 2002,(R) 2003,(R) 2004,(R) 2005,(R) 2006,(R) 2007,(R) 2008,...,(R) 2021,(P) 2022,(P) 2023,(P) 2024,(P) 2025,(P) 2026,(P) 2027,(P) 2028,(P) 2029,(P) 2030
0,Buses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total HCa,1.198,1.195,1.197,1.197,1.202,1.209,1.197,1.144,1.091,...,0.422,0.398,0.373,0.348,0.325,0.304,0.284,0.266,0.249,0.234
2,Exhaust CO,5.303,5.277,5.213,5.129,5.161,5.173,5.061,4.810,4.562,...,2.480,2.415,2.336,2.258,2.186,2.116,2.056,2.002,1.952,1.906
3,Exhaust NOx,26.112,25.037,23.956,22.469,21.598,20.671,19.412,17.984,16.711,...,6.433,6.212,5.852,5.496,5.174,4.864,4.505,4.182,3.865,3.561
4,Exhaust PM2.5,1.242,1.183,1.117,1.053,1.026,0.991,0.942,0.852,0.782,...,0.227,0.213,0.192,0.172,0.155,0.138,0.123,0.106,0.095,0.084
5,Brake Wear PM2.5,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,...,0.026,0.027,0.028,0.029,0.030,0.031,0.033,0.034,0.035,0.036
6,Tire Wear PM2.5,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,...,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003
7,Exhaust CO2,1557.343,1555.379,1552.564,1545.783,1547.839,1546.758,1545.141,1541.361,1540.592,...,1552.375,1546.049,1534.685,1518.545,1503.589,1489.341,1470.301,1457.110,1438.783,1424.291
8,Energy Consumption (Btu/mile),19909.315,19884.216,19848.200,19761.528,19787.805,19774.001,19753.317,19704.990,19695.171,...,19845.802,19764.916,19619.650,19413.324,19222.118,19039.948,18796.556,18627.912,18393.616,18208.350
9,Heavy-duty vehicles (other than buses),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df2 = df.rename(columns={"Unnamed: 0":"label"})
df2.head()

,label,(R) 2000,(R) 2001,(R) 2002,(R) 2003,(R) 2004,(R) 2005,(R) 2006,(R) 2007,(R) 2008,...,(R) 2021,(P) 2022,(P) 2023,(P) 2024,(P) 2025,(P) 2026,(P) 2027,(P) 2028,(P) 2029,(P) 2030
0,Buses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total HCa,1.198,1.195,1.197,1.197,1.202,1.209,1.197,1.144,1.091,...,0.422,0.398,0.373,0.348,0.325,0.304,0.284,0.266,0.249,0.234
2,Exhaust CO,5.303,5.277,5.213,5.129,5.161,5.173,5.061,4.810,4.562,...,2.480,2.415,2.336,2.258,2.186,2.116,2.056,2.002,1.952,1.906
3,Exhaust NOx,26.112,25.037,23.956,22.469,21.598,20.671,19.412,17.984,16.711,...,6.433,6.212,5.852,5.496,5.174,4.864,4.505,4.182,3.865,3.561
4,Exhaust PM2.5,1.242,1.183,1.117,1.053,1.026,0.991,0.942,0.852,0.782,...,0.227,0.213,0.192,0.172,0.155,0.138,0.123,0.106,0.095,0.084

In [14]:

df2["vehicle_group"] = df2["label"].where(
    df2["label"].str.contains("Buses|Heavy-duty", na=False)
).ffill()

In [17]:
df2.head(10)

,label,(R) 2000,(R) 2001,(R) 2002,(R) 2003,(R) 2004,(R) 2005,(R) 2006,(R) 2007,(R) 2008,...,(P) 2022,(P) 2023,(P) 2024,(P) 2025,(P) 2026,(P) 2027,(P) 2028,(P) 2029,(P) 2030,vehicle_group
0,Buses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Buses
1,Total HCa,1.198,1.195,1.197,1.197,1.202,1.209,1.197,1.144,1.091,...,0.398,0.373,0.348,0.325,0.304,0.284,0.266,0.249,0.234,Buses
2,Exhaust CO,5.303,5.277,5.213,5.129,5.161,5.173,5.061,4.810,4.562,...,2.415,2.336,2.258,2.186,2.116,2.056,2.002,1.952,1.906,Buses
3,Exhaust NOx,26.112,25.037,23.956,22.469,21.598,20.671,19.412,17.984,16.711,...,6.212,5.852,5.496,5.174,4.864,4.505,4.182,3.865,3.561,Buses
4,Exhaust PM2.5,1.242,1.183,1.117,1.053,1.026,0.991,0.942,0.852,0.782,...,0.213,0.192,0.172,0.155,0.138,0.123,0.106,0.095,0.084,Buses
5,Brake Wear PM2.5,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,...,0.027,0.028,0.029,0.030,0.031,0.033,0.034,0.035,0.036,Buses
6,Tire Wear PM2.5,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,...,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,Buses
7,Exhaust CO2,1557.343,1555.379,1552.564,1545.783,1547.839,1546.758,1545.141,1541.361,1540.592,...,1546.049,1534.685,1518.545,1503.589,1489.341,1470.301,1457.110,1438.783,1424.291,Buses
8,Energy Consumption (Btu/mile),19909.315,19884.216,19848.200,19761.528,19787.805,19774.001,19753.317,19704.990,19695.171,...,19764.916,19619.650,19413.324,19222.118,19039.948,18796.556,18627.912,18393.616,18208.350,Buses
9,Heavy-duty vehicles (other than buses),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Heavy-duty vehicles (other than buses)

In [18]:
co2_rows = df2[df2["label"] == "Exhaust CO2"]

In [19]:
co2_rows.head(10)

,label,(R) 2000,(R) 2001,(R) 2002,(R) 2003,(R) 2004,(R) 2005,(R) 2006,(R) 2007,(R) 2008,...,(P) 2022,(P) 2023,(P) 2024,(P) 2025,(P) 2026,(P) 2027,(P) 2028,(P) 2029,(P) 2030,vehicle_group
7,Exhaust CO2,1557.343,1555.379,1552.564,1545.783,1547.839,1546.758,1545.141,1541.361,1540.592,...,1546.049,1534.685,1518.545,1503.589,1489.341,1470.301,1457.110,1438.783,1424.291,Buses
16,Exhaust CO2,1676.602,1677.044,1669.223,1664.819,1664.828,1666.594,1650.444,1658.720,1648.951,...,1475.975,1449.696,1418.751,1390.295,1364.020,1334.047,1308.028,1286.692,1269.225,Heavy-duty vehicles (other than buses)

In [20]:
year_cols = co2_rows.columns.difference(["label", "vehicle_group"])

bus_values = co2_rows.loc[
    co2_rows["vehicle_group"].str.contains("Buses"),
    year_cols
].to_numpy().flatten()

heavy_values = co2_rows.loc[
    co2_rows["vehicle_group"].str.contains("Heavy-duty"),
    year_cols
].to_numpy().flatten()

In [22]:
large_values = np.concatenate([bus_values, heavy_values])

large_co2 = trim_mean(large_values, 0.1)  # 10% trim

In [23]:
large_df = pd.DataFrame({
    "Vehicle Type": ["Large"],
    "CO2 (g/mi)": [round(large_co2, 4)]
})

large_df.head()

  Vehicle Type  CO2 (g/mi)
0        Large   1557.3849

In [24]:
data2 = pd.read_csv("C:/Users/clair/Senior-Project/EPA Data Cleaning/Clean_outlier/carbon_emissions.csv")
df2 = pd.DataFrame(data2)
df2.head()

  Vehicle Type  CO2 (g/mi)
0        Small  285.897159
1       Medium  341.316992

In [25]:
merged = pd.concat([large_df,df2],ignore_index=True)
merged.head()

  Vehicle Type   CO2 (g/mi)
0        Large  1557.384900
1        Small   285.897159
2       Medium   341.316992

In [26]:
merged.to_csv('carbon_emissions_final.csv')